authentication:
  api_keys:
    enabled: true
    rate_limiting: true
    usage_tracking: true
  sso:
    oauth2: true
    oidc: true
    providers:
    - google
    - microsoft
    - github
    saml: true
compliance:
  audit_logging: true
  data_retention: 90_days
  gdpr: true
  right_to_deletion: true
  soc2: true
enterprise_monitoring:
  audit_trail: true
  cost_centers: true
  custom_alerts: true
  sla_monitoring: true
  usage_analytics: true
security:
  ddos_protection: true
  input_validation: true
  output_sanitization: true
  rate_limiting:
    global: 1000/minute
    per_ip: 50/minute
    per_user: 100/minute
